all:
	#g++  --std=c++11 depth_map.cpp -lrealsense2 -lopencv_core -lopencv_imgproc -lopencv_highgui -o depth_map
	#g++  --std=c++11 quick_view.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui -o quick_view
	g++  --std=c++11 capture_images.cpp -lrealsense2 -lopencv_core -lopencv_imgproc -lopencv_highgui -o capture_images