// Generated by gencpp from file system_state/DetectTargetResponse.msg
// DO NOT EDIT!


#ifndef SYSTEM_STATE_MESSAGE_DETECTTARGETRESPONSE_H
#define SYSTEM_STATE_MESSAGE_DETECTTARGETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_state
{
template <class ContainerAllocator>
struct DetectTargetResponse_
{
  typedef DetectTargetResponse_<ContainerAllocator> Type;

  DetectTargetResponse_()
    : json_state()
    , X(0)
    , Y(0)
    , Z(0)  {
    }
  DetectTargetResponse_(const ContainerAllocator& _alloc)
    : json_state(_alloc)
    , X(0)
    , Y(0)
    , Z(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _json_state_type;
  _json_state_type json_state;

   typedef int64_t _X_type;
  _X_type X;

   typedef int64_t _Y_type;
  _Y_type Y;

   typedef int64_t _Z_type;
  _Z_type Z;





  typedef boost::shared_ptr< ::system_state::DetectTargetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_state::DetectTargetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectTargetResponse_

typedef ::system_state::DetectTargetResponse_<std::allocator<void> > DetectTargetResponse;

typedef boost::shared_ptr< ::system_state::DetectTargetResponse > DetectTargetResponsePtr;
typedef boost::shared_ptr< ::system_state::DetectTargetResponse const> DetectTargetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_state::DetectTargetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_state::DetectTargetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace system_state

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'system_state': ['/home/ubuntu/SPARO/ROS_modules/src/system_state/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::system_state::DetectTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_state::DetectTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_state::DetectTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_state::DetectTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_state::DetectTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_state::DetectTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_state::DetectTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "771f4495ccebaf28e2e698ac883f1d20";
  }

  static const char* value(const ::system_state::DetectTargetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x771f4495ccebaf28ULL;
  static const uint64_t static_value2 = 0xe2e698ac883f1d20ULL;
};

template<class ContainerAllocator>
struct DataType< ::system_state::DetectTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_state/DetectTargetResponse";
  }

  static const char* value(const ::system_state::DetectTargetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_state::DetectTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string json_state\n\
int64 X\n\
int64 Y\n\
int64 Z\n\
";
  }

  static const char* value(const ::system_state::DetectTargetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_state::DetectTargetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.json_state);
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.Z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectTargetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_state::DetectTargetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_state::DetectTargetResponse_<ContainerAllocator>& v)
  {
    s << indent << "json_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.json_state);
    s << indent << "X: ";
    Printer<int64_t>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Y);
    s << indent << "Z: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_STATE_MESSAGE_DETECTTARGETRESPONSE_H
