// Generated by gencpp from file system_state/DetectTarget.msg
// DO NOT EDIT!


#ifndef SYSTEM_STATE_MESSAGE_DETECTTARGET_H
#define SYSTEM_STATE_MESSAGE_DETECTTARGET_H

#include <ros/service_traits.h>


#include <system_state/DetectTargetRequest.h>
#include <system_state/DetectTargetResponse.h>


namespace system_state
{

struct DetectTarget
{

typedef DetectTargetRequest Request;
typedef DetectTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectTarget
} // namespace system_state


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::system_state::DetectTarget > {
  static const char* value()
  {
    return "771f4495ccebaf28e2e698ac883f1d20";
  }

  static const char* value(const ::system_state::DetectTarget&) { return value(); }
};

template<>
struct DataType< ::system_state::DetectTarget > {
  static const char* value()
  {
    return "system_state/DetectTarget";
  }

  static const char* value(const ::system_state::DetectTarget&) { return value(); }
};


// service_traits::MD5Sum< ::system_state::DetectTargetRequest> should match 
// service_traits::MD5Sum< ::system_state::DetectTarget > 
template<>
struct MD5Sum< ::system_state::DetectTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::system_state::DetectTarget >::value();
  }
  static const char* value(const ::system_state::DetectTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_state::DetectTargetRequest> should match 
// service_traits::DataType< ::system_state::DetectTarget > 
template<>
struct DataType< ::system_state::DetectTargetRequest>
{
  static const char* value()
  {
    return DataType< ::system_state::DetectTarget >::value();
  }
  static const char* value(const ::system_state::DetectTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::system_state::DetectTargetResponse> should match 
// service_traits::MD5Sum< ::system_state::DetectTarget > 
template<>
struct MD5Sum< ::system_state::DetectTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::system_state::DetectTarget >::value();
  }
  static const char* value(const ::system_state::DetectTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_state::DetectTargetResponse> should match 
// service_traits::DataType< ::system_state::DetectTarget > 
template<>
struct DataType< ::system_state::DetectTargetResponse>
{
  static const char* value()
  {
    return DataType< ::system_state::DetectTarget >::value();
  }
  static const char* value(const ::system_state::DetectTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SYSTEM_STATE_MESSAGE_DETECTTARGET_H
