// Generated by gencpp from file system_state/LoadMission.msg
// DO NOT EDIT!


#ifndef SYSTEM_STATE_MESSAGE_LOADMISSION_H
#define SYSTEM_STATE_MESSAGE_LOADMISSION_H

#include <ros/service_traits.h>


#include <system_state/LoadMissionRequest.h>
#include <system_state/LoadMissionResponse.h>


namespace system_state
{

struct LoadMission
{

typedef LoadMissionRequest Request;
typedef LoadMissionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadMission
} // namespace system_state


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::system_state::LoadMission > {
  static const char* value()
  {
    return "cf76547124a8eccb32585a0d744f179b";
  }

  static const char* value(const ::system_state::LoadMission&) { return value(); }
};

template<>
struct DataType< ::system_state::LoadMission > {
  static const char* value()
  {
    return "system_state/LoadMission";
  }

  static const char* value(const ::system_state::LoadMission&) { return value(); }
};


// service_traits::MD5Sum< ::system_state::LoadMissionRequest> should match 
// service_traits::MD5Sum< ::system_state::LoadMission > 
template<>
struct MD5Sum< ::system_state::LoadMissionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::system_state::LoadMission >::value();
  }
  static const char* value(const ::system_state::LoadMissionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_state::LoadMissionRequest> should match 
// service_traits::DataType< ::system_state::LoadMission > 
template<>
struct DataType< ::system_state::LoadMissionRequest>
{
  static const char* value()
  {
    return DataType< ::system_state::LoadMission >::value();
  }
  static const char* value(const ::system_state::LoadMissionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::system_state::LoadMissionResponse> should match 
// service_traits::MD5Sum< ::system_state::LoadMission > 
template<>
struct MD5Sum< ::system_state::LoadMissionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::system_state::LoadMission >::value();
  }
  static const char* value(const ::system_state::LoadMissionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_state::LoadMissionResponse> should match 
// service_traits::DataType< ::system_state::LoadMission > 
template<>
struct DataType< ::system_state::LoadMissionResponse>
{
  static const char* value()
  {
    return DataType< ::system_state::LoadMission >::value();
  }
  static const char* value(const ::system_state::LoadMissionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SYSTEM_STATE_MESSAGE_LOADMISSION_H
