// Generated by gencpp from file system_state/MoveRobotResponse.msg
// DO NOT EDIT!


#ifndef SYSTEM_STATE_MESSAGE_MOVEROBOTRESPONSE_H
#define SYSTEM_STATE_MESSAGE_MOVEROBOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_state
{
template <class ContainerAllocator>
struct MoveRobotResponse_
{
  typedef MoveRobotResponse_<ContainerAllocator> Type;

  MoveRobotResponse_()
    : reached_position(false)  {
    }
  MoveRobotResponse_(const ContainerAllocator& _alloc)
    : reached_position(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reached_position_type;
  _reached_position_type reached_position;





  typedef boost::shared_ptr< ::system_state::MoveRobotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_state::MoveRobotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobotResponse_

typedef ::system_state::MoveRobotResponse_<std::allocator<void> > MoveRobotResponse;

typedef boost::shared_ptr< ::system_state::MoveRobotResponse > MoveRobotResponsePtr;
typedef boost::shared_ptr< ::system_state::MoveRobotResponse const> MoveRobotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_state::MoveRobotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_state::MoveRobotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace system_state

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'system_state': ['/home/ubuntu/SPARO/ROS_modules/src/system_state/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::system_state::MoveRobotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_state::MoveRobotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_state::MoveRobotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_state::MoveRobotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_state::MoveRobotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_state::MoveRobotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_state::MoveRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad0686c29d6de7db1f1ccb258f723d7f";
  }

  static const char* value(const ::system_state::MoveRobotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad0686c29d6de7dbULL;
  static const uint64_t static_value2 = 0x1f1ccb258f723d7fULL;
};

template<class ContainerAllocator>
struct DataType< ::system_state::MoveRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_state/MoveRobotResponse";
  }

  static const char* value(const ::system_state::MoveRobotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_state::MoveRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reached_position\n\
";
  }

  static const char* value(const ::system_state::MoveRobotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_state::MoveRobotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reached_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_state::MoveRobotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_state::MoveRobotResponse_<ContainerAllocator>& v)
  {
    s << indent << "reached_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reached_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_STATE_MESSAGE_MOVEROBOTRESPONSE_H
