// Generated by gencpp from file system_state/MoveRobotRequest.msg
// DO NOT EDIT!


#ifndef SYSTEM_STATE_MESSAGE_MOVEROBOTREQUEST_H
#define SYSTEM_STATE_MESSAGE_MOVEROBOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_state
{
template <class ContainerAllocator>
struct MoveRobotRequest_
{
  typedef MoveRobotRequest_<ContainerAllocator> Type;

  MoveRobotRequest_()
    : X(0)
    , Y(0)  {
    }
  MoveRobotRequest_(const ContainerAllocator& _alloc)
    : X(0)
    , Y(0)  {
  (void)_alloc;
    }



   typedef int64_t _X_type;
  _X_type X;

   typedef int64_t _Y_type;
  _Y_type Y;





  typedef boost::shared_ptr< ::system_state::MoveRobotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_state::MoveRobotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobotRequest_

typedef ::system_state::MoveRobotRequest_<std::allocator<void> > MoveRobotRequest;

typedef boost::shared_ptr< ::system_state::MoveRobotRequest > MoveRobotRequestPtr;
typedef boost::shared_ptr< ::system_state::MoveRobotRequest const> MoveRobotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_state::MoveRobotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_state::MoveRobotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace system_state

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'system_state': ['/home/ubuntu/SPARO/ROS_modules/src/system_state/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::system_state::MoveRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_state::MoveRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_state::MoveRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_state::MoveRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_state::MoveRobotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_state::MoveRobotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_state::MoveRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6dab1705b6ff76dc460c7c88a89a4a61";
  }

  static const char* value(const ::system_state::MoveRobotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6dab1705b6ff76dcULL;
  static const uint64_t static_value2 = 0x460c7c88a89a4a61ULL;
};

template<class ContainerAllocator>
struct DataType< ::system_state::MoveRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_state/MoveRobotRequest";
  }

  static const char* value(const ::system_state::MoveRobotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_state::MoveRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 X\n\
int64 Y\n\
";
  }

  static const char* value(const ::system_state::MoveRobotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_state::MoveRobotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_state::MoveRobotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_state::MoveRobotRequest_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<int64_t>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_STATE_MESSAGE_MOVEROBOTREQUEST_H
