// Generated by gencpp from file system_state/MoveRobot.msg
// DO NOT EDIT!


#ifndef SYSTEM_STATE_MESSAGE_MOVEROBOT_H
#define SYSTEM_STATE_MESSAGE_MOVEROBOT_H

#include <ros/service_traits.h>


#include <system_state/MoveRobotRequest.h>
#include <system_state/MoveRobotResponse.h>


namespace system_state
{

struct MoveRobot
{

typedef MoveRobotRequest Request;
typedef MoveRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveRobot
} // namespace system_state


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::system_state::MoveRobot > {
  static const char* value()
  {
    return "5aa155b242bcdec0a89321f704bbe675";
  }

  static const char* value(const ::system_state::MoveRobot&) { return value(); }
};

template<>
struct DataType< ::system_state::MoveRobot > {
  static const char* value()
  {
    return "system_state/MoveRobot";
  }

  static const char* value(const ::system_state::MoveRobot&) { return value(); }
};


// service_traits::MD5Sum< ::system_state::MoveRobotRequest> should match 
// service_traits::MD5Sum< ::system_state::MoveRobot > 
template<>
struct MD5Sum< ::system_state::MoveRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::system_state::MoveRobot >::value();
  }
  static const char* value(const ::system_state::MoveRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_state::MoveRobotRequest> should match 
// service_traits::DataType< ::system_state::MoveRobot > 
template<>
struct DataType< ::system_state::MoveRobotRequest>
{
  static const char* value()
  {
    return DataType< ::system_state::MoveRobot >::value();
  }
  static const char* value(const ::system_state::MoveRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::system_state::MoveRobotResponse> should match 
// service_traits::MD5Sum< ::system_state::MoveRobot > 
template<>
struct MD5Sum< ::system_state::MoveRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::system_state::MoveRobot >::value();
  }
  static const char* value(const ::system_state::MoveRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_state::MoveRobotResponse> should match 
// service_traits::DataType< ::system_state::MoveRobot > 
template<>
struct DataType< ::system_state::MoveRobotResponse>
{
  static const char* value()
  {
    return DataType< ::system_state::MoveRobot >::value();
  }
  static const char* value(const ::system_state::MoveRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SYSTEM_STATE_MESSAGE_MOVEROBOT_H
