// Generated by gencpp from file system_state/MoveEndEffector.msg
// DO NOT EDIT!


#ifndef SYSTEM_STATE_MESSAGE_MOVEENDEFFECTOR_H
#define SYSTEM_STATE_MESSAGE_MOVEENDEFFECTOR_H

#include <ros/service_traits.h>


#include <system_state/MoveEndEffectorRequest.h>
#include <system_state/MoveEndEffectorResponse.h>


namespace system_state
{

struct MoveEndEffector
{

typedef MoveEndEffectorRequest Request;
typedef MoveEndEffectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveEndEffector
} // namespace system_state


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::system_state::MoveEndEffector > {
  static const char* value()
  {
    return "515108492c7d4ad3a4f126e6820b3140";
  }

  static const char* value(const ::system_state::MoveEndEffector&) { return value(); }
};

template<>
struct DataType< ::system_state::MoveEndEffector > {
  static const char* value()
  {
    return "system_state/MoveEndEffector";
  }

  static const char* value(const ::system_state::MoveEndEffector&) { return value(); }
};


// service_traits::MD5Sum< ::system_state::MoveEndEffectorRequest> should match 
// service_traits::MD5Sum< ::system_state::MoveEndEffector > 
template<>
struct MD5Sum< ::system_state::MoveEndEffectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::system_state::MoveEndEffector >::value();
  }
  static const char* value(const ::system_state::MoveEndEffectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_state::MoveEndEffectorRequest> should match 
// service_traits::DataType< ::system_state::MoveEndEffector > 
template<>
struct DataType< ::system_state::MoveEndEffectorRequest>
{
  static const char* value()
  {
    return DataType< ::system_state::MoveEndEffector >::value();
  }
  static const char* value(const ::system_state::MoveEndEffectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::system_state::MoveEndEffectorResponse> should match 
// service_traits::MD5Sum< ::system_state::MoveEndEffector > 
template<>
struct MD5Sum< ::system_state::MoveEndEffectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::system_state::MoveEndEffector >::value();
  }
  static const char* value(const ::system_state::MoveEndEffectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::system_state::MoveEndEffectorResponse> should match 
// service_traits::DataType< ::system_state::MoveEndEffector > 
template<>
struct DataType< ::system_state::MoveEndEffectorResponse>
{
  static const char* value()
  {
    return DataType< ::system_state::MoveEndEffector >::value();
  }
  static const char* value(const ::system_state::MoveEndEffectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SYSTEM_STATE_MESSAGE_MOVEENDEFFECTOR_H
