// Generated by gencpp from file system_state/SetTargetStateResponse.msg
// DO NOT EDIT!


#ifndef SYSTEM_STATE_MESSAGE_SETTARGETSTATERESPONSE_H
#define SYSTEM_STATE_MESSAGE_SETTARGETSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_state
{
template <class ContainerAllocator>
struct SetTargetStateResponse_
{
  typedef SetTargetStateResponse_<ContainerAllocator> Type;

  SetTargetStateResponse_()
    : state_reached(0)  {
    }
  SetTargetStateResponse_(const ContainerAllocator& _alloc)
    : state_reached(0)  {
  (void)_alloc;
    }



   typedef int8_t _state_reached_type;
  _state_reached_type state_reached;





  typedef boost::shared_ptr< ::system_state::SetTargetStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_state::SetTargetStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargetStateResponse_

typedef ::system_state::SetTargetStateResponse_<std::allocator<void> > SetTargetStateResponse;

typedef boost::shared_ptr< ::system_state::SetTargetStateResponse > SetTargetStateResponsePtr;
typedef boost::shared_ptr< ::system_state::SetTargetStateResponse const> SetTargetStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_state::SetTargetStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_state::SetTargetStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace system_state

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'system_state': ['/home/ubuntu/SPARO/ROS_modules/src/system_state/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::system_state::SetTargetStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_state::SetTargetStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_state::SetTargetStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_state::SetTargetStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_state::SetTargetStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_state::SetTargetStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_state::SetTargetStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d14741f21a107d8dfdecf2120a39d20d";
  }

  static const char* value(const ::system_state::SetTargetStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd14741f21a107d8dULL;
  static const uint64_t static_value2 = 0xfdecf2120a39d20dULL;
};

template<class ContainerAllocator>
struct DataType< ::system_state::SetTargetStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_state/SetTargetStateResponse";
  }

  static const char* value(const ::system_state::SetTargetStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_state::SetTargetStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 state_reached\n\
";
  }

  static const char* value(const ::system_state::SetTargetStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_state::SetTargetStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_reached);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargetStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_state::SetTargetStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_state::SetTargetStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "state_reached: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state_reached);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_STATE_MESSAGE_SETTARGETSTATERESPONSE_H
