# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from Serial import *
from SetPort import *
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, serial_thread):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.dcmotor_directions = QtWidgets.QGroupBox(self.centralwidget)
        self.dcmotor_directions.setObjectName("dcmotor_directions")
        self.dcmotor_forward = QtWidgets.QRadioButton(self.dcmotor_directions)
        self.dcmotor_forward.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.dcmotor_forward.setObjectName("dcmotor_forward")
        self.dcmotor_reverse = QtWidgets.QRadioButton(self.dcmotor_directions)
        self.dcmotor_reverse.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.dcmotor_reverse.setObjectName("dcmotor_reverse")
        self.gridLayout.addWidget(self.dcmotor_directions, 7, 2, 1, 1)
        self.stepper_directions = QtWidgets.QGroupBox(self.centralwidget)
        self.stepper_directions.setMinimumSize(QtCore.QSize(100, 75))
        self.stepper_directions.setObjectName("stepper_directions")
        self.stepper_forward = QtWidgets.QRadioButton(self.stepper_directions)
        self.stepper_forward.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.stepper_forward.setChecked(True)
        self.stepper_forward.setObjectName("stepper_forward")
        self.stepper_reverse = QtWidgets.QRadioButton(self.stepper_directions)
        self.stepper_reverse.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.stepper_reverse.setObjectName("stepper_reverse")
        self.gridLayout.addWidget(self.stepper_directions, 7, 0, 1, 1)
        self.rcservo_angle_label = QtWidgets.QLabel(self.centralwidget)
        self.rcservo_angle_label.setObjectName("rcservo_angle_label")
        self.gridLayout.addWidget(self.rcservo_angle_label, 4, 1, 1, 1, QtCore.Qt.AlignTop)
        self.rcservo_position_button = QtWidgets.QPushButton(self.centralwidget)
        self.rcservo_position_button.setObjectName("rcservo_position_button")
        self.gridLayout.addWidget(self.rcservo_position_button, 8, 1, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout.addWidget(self.lcdNumber_3, 10, 2, 1, 1)
        self.rcservo_controls_label = QtWidgets.QLabel(self.centralwidget)
        self.rcservo_controls_label.setObjectName("rcservo_controls_label")
        self.gridLayout.addWidget(self.rcservo_controls_label, 0, 1, 1, 1)
        self.dcmotor_controls_label = QtWidgets.QLabel(self.centralwidget)
        self.dcmotor_controls_label.setObjectName("dcmotor_controls_label")
        self.gridLayout.addWidget(self.dcmotor_controls_label, 0, 2, 1, 1)
        self.rcservo_degrees_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.rcservo_degrees_spin.setObjectName("rcservo_degrees_spin")
        self.gridLayout.addWidget(self.rcservo_degrees_spin, 3, 1, 1, 1)
        self.dcmotor_degrees_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.dcmotor_degrees_spin.setObjectName("dcmotor_degrees_spin")
        self.gridLayout.addWidget(self.dcmotor_degrees_spin, 3, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 9, 1, 1, 1, QtCore.Qt.AlignBottom)
        self.dcmotor_degrees_label = QtWidgets.QLabel(self.centralwidget)
        self.dcmotor_degrees_label.setObjectName("dcmotor_degrees_label")
        self.gridLayout.addWidget(self.dcmotor_degrees_label, 4, 2, 1, 1, QtCore.Qt.AlignTop)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 10, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 10, 1, 1, 1)
        self.stepper_position_button = QtWidgets.QPushButton(self.centralwidget)
        self.stepper_position_button.setObjectName("stepper_position_button")
        self.gridLayout.addWidget(self.stepper_position_button, 8, 0, 1, 1)
        self.stepper_degrees_label = QtWidgets.QLabel(self.centralwidget)
        self.stepper_degrees_label.setObjectName("stepper_degrees_label")
        self.gridLayout.addWidget(self.stepper_degrees_label, 4, 0, 1, 1, QtCore.Qt.AlignTop)
        self.stepper_controls_label = QtWidgets.QLabel(self.centralwidget)
        self.stepper_controls_label.setObjectName("stepper_controls_label")
        self.gridLayout.addWidget(self.stepper_controls_label, 0, 0, 1, 1)
        self.stepper_degrees_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.stepper_degrees_spin.setMaximum(9999)
        self.stepper_degrees_spin.setObjectName("stepper_degrees_spin")
        self.gridLayout.addWidget(self.stepper_degrees_spin, 3, 0, 1, 1)
        self.dcmotor_position_button = QtWidgets.QPushButton(self.centralwidget)
        self.dcmotor_position_button.setObjectName("dcmotor_position_button")
        self.gridLayout.addWidget(self.dcmotor_position_button, 8, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 2, 1, 1, QtCore.Qt.AlignTop)
        self.plainTextEdit = QtWidgets.QLabel(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 11, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        self.menuConnect = QtWidgets.QMenu(self.menubar)
        self.menuConnect.setObjectName("menuConnect")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConfigure_Serial_Port = QtWidgets.QAction(MainWindow)
        self.actionConfigure_Serial_Port.setObjectName("actionConfigure_Serial_Port")
        self.menuConnect.addAction(self.actionConfigure_Serial_Port)
        self.menubar.addAction(self.menuConnect.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        serial_thread.set_output(self.plainTextEdit)
        self.actionConfigure_Serial_Port.triggered.connect(build_show_serial_config(serial_thread))

        self.stepper_position_button.clicked.connect(serial_thread.build_stepper_command(self.stepper_forward, self.stepper_reverse, self.stepper_degrees_spin))
        self.rcservo_position_button.clicked.connect(serial_thread.build_rcservo_command(self.rcservo_degrees_spin))
        self.dcmotor_position_button.clicked.connect(serial_thread.build_dcmotor_command(self.dcmotor_forward, self.dcmotor_reverse, self.dcmotor_degrees_spin, self.spinBox))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Motor Lab Controls"))
        self.dcmotor_directions.setTitle(_translate("MainWindow", "Direction"))
        self.dcmotor_forward.setText(_translate("MainWindow", "Forward"))
        self.dcmotor_reverse.setText(_translate("MainWindow", "Reverse"))
        self.stepper_directions.setTitle(_translate("MainWindow", "Direction"))
        self.stepper_forward.setText(_translate("MainWindow", "Forward"))
        self.stepper_reverse.setText(_translate("MainWindow", "Rerverse"))
        self.rcservo_angle_label.setText(_translate("MainWindow", "Angle"))
        self.rcservo_position_button.setText(_translate("MainWindow", "Set Servo Position"))
        self.rcservo_controls_label.setText(_translate("MainWindow", "RC Servo Controls"))
        self.dcmotor_controls_label.setText(_translate("MainWindow", "DC Motor Controls"))
        self.label_2.setText(_translate("MainWindow", "Servo Angle"))
        self.dcmotor_degrees_label.setText(_translate("MainWindow", "Degrees Rotation"))
        self.stepper_position_button.setText(_translate("MainWindow", "Set Stepper Position"))
        self.stepper_degrees_label.setText(_translate("MainWindow", "Degrees Rotation"))
        self.stepper_controls_label.setText(_translate("MainWindow", "Stepper Motor Controls"))
        self.dcmotor_position_button.setText(_translate("MainWindow", "Set DC Motor Position"))
        self.label_3.setText(_translate("MainWindow", "Speed"))
        self.menuConnect.setTitle(_translate("MainWindow", "Connect"))
        self.actionConfigure_Serial_Port.setText(_translate("MainWindow", "Configure Serial Port"))

